### ISSUE TITLE
Texto saindo da área de conteúdo do livro (invadindo bordas)

### ISSUE THREAD

**Issue by RafaelHac** [ufpb-computacao/matematica-elementar-livro#10]
. link na seção 5.6
. Tabela sobrepondo footnote seção 6.2 (pag 131)
. Tabela ultrapassando borda inferior na seção 6.5

**Comment by edusantana** [comment]
Outros commits relacionados a este bug: https://github.com/edusantana/matematica-elementar-livro/commit/f8be95accc6fff2599a20b251be454069108b453 e https://github.com/edusantana/matematica-elementar-livro/commit/9566801536c9177a4e244944ba76fa224ff169f1

Oi @RafaelHac , eu não corrigi todos os problemas relacionados ao ítem 6.5, você poderia corrigir o restante com base na solução que indiquei em https://github.com/edusantana/matematica-elementar-livro/commit/9deeea213246ac7b3d2a12bdb3ed7598ff860545 ?
