### ISSUE TITLE
cap2 [Link não aparece no texto] 

### ISSUE THREAD

**Issue by glaucosoares** [ufpb-computacao/matematica-elementar-livro#61]
Versão do livro: v2.3.1
Página: 30

A Dica na sessão 2.2.1.1 o texto indica um link para uma vídeo aula, no entanto é apresentado o seguinte texto:

Existe videoaula sobre Sintaxe da Lógica Proposicional na [?informaltable] [??].

Aparentemente a ferramenta não reconheceu o link por estar mal formatado.

**Comment by edusantana** [comment]
Oi @glaucosoares recomendo utilizar a versão [v2.3.8](https://github.com/ufpb-computacao/matematica-elementar-livro/releases/download/v2.3.8/matematica-elementar-livro-v2.3.8.pdf), em que podemos verificar (página 51) que o erro não existe mais: 

```
Dica
Existe videoaula sobre Sintaxe da Lógica Proposicional na Tabela 2.1 [35].
```

**Comment by glaucosoares** [comment]
ok, @edusantana. obrigado pela dica :)
