### ISSUE TITLE
Debug Capítulo 7

### ISSUE THREAD

**Issue by RafaelHac** [ufpb-computacao/matematica-elementar-livro#8]

**Comment by edusantana** [comment]
oi @RafaelHac 

Estou vendo que finalizou o capítulo 7, quais as pendências que temos?

**Comment by RafaelHac** [comment]
estou finalizando o capítulo 6, fiz o 7 primeiro por ser um capítulo mais
simples

finalizarei o 6 nesta semana ainda

On Thu, Feb 20, 2014 at 8:13 AM, Eduardo de Santana Medeiros Alexandre <
notifications@github.com> wrote:

> oi @RafaelHac https://github.com/RafaelHac
> 
> Estou vendo que finalizou o capítulo 7, quais as pendências que temos?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/edusantana/matematica-elementar-livro/issues/8#issuecomment-35610196
> .

## 

Rafael Henrique Assis de Castro
